"""Guard tests: hand-written docs must derive the version from {{ version }}, never hardcode it.

The docs-sync pass version-pinned example URLs to match the Pydantic model output. Hand-written
pages template the version via zensical macros (`{{ version }}`, fed by `main.py`'s `define_env`),
so they track `iscc_schema.__version__` automatically. These tests catch a contributor re-hardcoding
the current version, which would silently go stale at the next release. README is special-cased: it
renders on GitHub/PyPI where macros never run, so it must carry no version-pinned ISCC URL at all.
"""

import pathlib
import re

import iscc_schema as iss

ROOT = pathlib.Path(__file__).parent.parent

# Hand-written, macro-rendered doc sources (NOT generated by tools/build_docs.py).
TEMPLATED_DOCS = [
    "docs/guide.md",
    "docs/examples/index.md",
    "docs/versioning.md",
]

# A version-pinned ISCC schema/context URL, capturing the X.Y.Z version segment.
PINNED_URL_RE = re.compile(
    r"purl\.org/iscc/(?:schema|context)/[\w-]*?(\d+\.\d+\.\d+)\.(?:json|jsonld)"
)


def test_templated_docs_have_no_current_version_url():
    """Hand-written docs must use {{ version }}, never a URL pinned to the current version.

    Illustrative URLs pinned to a different version (e.g. versioning.md's 0.5.0 examples) are
    allowed; only a URL matching the live __version__ would go stale on the next release.
    """
    version = iss.__version__
    for rel in TEMPLATED_DOCS:
        text = (ROOT / rel).read_text(encoding="utf-8")
        pinned = [m.group(0) for m in PINNED_URL_RE.finditer(text) if m.group(1) == version]
        assert not pinned, (
            f"{rel} hardcodes the current version {version} in {pinned}; "
            "use {{ version }} so it tracks iscc_schema.__version__."
        )


def test_readme_has_no_versioned_iscc_url():
    """README renders where macros do not run, so it must carry no version-pinned ISCC URL."""
    text = (ROOT / "README.md").read_text(encoding="utf-8")
    pinned = PINNED_URL_RE.findall(text)
    assert not pinned, (
        f"README.md hardcodes version-pinned ISCC URL(s) {pinned}; keep it version-free "
        "(macros do not run on GitHub/PyPI)."
    )
