# -*- coding: utf-8 -*-
"""Custom BaseModel with JSON-LD alias serialization, JCS canonicalization, and coercion."""

import json
import types
from functools import lru_cache
from typing import ClassVar, Union, get_args, get_origin

import jcs
from pydantic import BaseModel as PydanticBaseModel, ConfigDict, model_validator


def _allows_list(annotation):
    # type: (object) -> bool
    """Return True if a type annotation accepts a list value."""
    origin = get_origin(annotation)
    if origin is list:
        return True
    if origin in (Union, types.UnionType):
        return any(_allows_list(arg) for arg in get_args(annotation))
    return False


@lru_cache(maxsize=None)
def _field_normalization_policy(cls):
    # type: (type[BaseModel]) -> tuple[frozenset[str], frozenset[str]]
    """Return declared input keys and required list keys for a model class."""
    declared_keys = set()
    required_list_keys = set()
    for name, field in cls.model_fields.items():
        keys = {name}
        if isinstance(field.alias, str):
            keys.add(field.alias)
        declared_keys.update(keys)
        if field.is_required() and _allows_list(field.annotation):
            required_list_keys.update(keys)
    return frozenset(declared_keys), frozenset(required_list_keys)


class BaseModel(PydanticBaseModel):
    """Overrides for autogenerated Pydantic Models."""

    _default_ld: ClassVar[bool] = True

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        use_enum_values=True,
        from_attributes=True,
        populate_by_name=True,
    )

    @model_validator(mode="before")
    @classmethod
    def empty_string_to_default(cls, values):
        # type: (dict) -> dict
        """Convert falsy declared field values to None while preserving extension data."""
        if not isinstance(values, dict):
            return values
        declared_keys, required_list_keys = _field_normalization_policy(cls)
        return {
            k: (
                v
                if (
                    k not in declared_keys
                    or v
                    or (isinstance(v, int) and not isinstance(v, bool))
                    or (isinstance(v, list) and k in required_list_keys)
                )
                else None
            )
            for k, v in values.items()
        }

    def _apply_ld(self, data, ld):
        # type: (dict, bool|None) -> dict
        """Strip or keep JSON-LD fields based on ld flag. Inject $schema when compact."""
        use_ld = self._default_ld if ld is None else ld
        if not use_ld:
            for field in ("@context", "@type"):
                data.pop(field, None)
            if "$schema" not in data and hasattr(self, "schema_"):
                data = {"$schema": self.schema_, **data}
        return data

    def dict(self, *args, exclude_none=True, exclude_unset=True, by_alias=True, ld=None, **kwargs):
        # type: (...) -> dict
        """Serialize to dict. Use ld=True for full JSON-LD, ld=False for compact JSON."""
        data = self.model_dump(
            *args,
            exclude_none=exclude_none,
            exclude_unset=exclude_unset,
            by_alias=by_alias,
            **kwargs,
        )
        return self._apply_ld(data, ld)

    def json(self, *args, exclude_none=True, by_alias=True, ld=None, indent=None, **kwargs):
        # type: (...) -> str
        """Serialize to JSON string. Use ld=True for full JSON-LD, ld=False for compact JSON."""
        use_ld = self._default_ld if ld is None else ld
        if use_ld:
            return self.model_dump_json(
                *args,
                exclude_none=exclude_none,
                by_alias=by_alias,
                indent=indent,
                **kwargs,
            )
        exclude_unset = kwargs.pop("exclude_unset", False)
        data = self.dict(
            *args,
            exclude_none=exclude_none,
            exclude_unset=exclude_unset,
            by_alias=by_alias,
            ld=False,
            **kwargs,
        )
        separators = (",", ":") if indent is None else (",", ": ")
        return json.dumps(data, separators=separators, indent=indent)

    def jcs(self, ld=None):
        # type: (bool|None) -> bytes
        """Create JCS canonicalized JSON bytestring."""
        use_ld = self._default_ld if ld is None else ld
        data = self.dict(exclude_unset=False, ld=use_ld)
        ser = jcs.canonicalize(data)
        des = json.loads(ser)
        if des != data:
            raise ValueError(f"Not canonicalizable {data} round-trips to {des}")
        return ser

    @property
    def iscc_obj(self):
        # type: () -> "iscc_core.Code"
        """Convenience method that wraps an ISCC string in an iscc_core.Code object.

        :return: `iscc_core.Code` object if the iscc-core package is installed
        :rtype: iscc_core.Code
        :raise: `ImportError` if iscc-core package is not installed.
        """
        try:
            from iscc_core import Code
        except ImportError:
            raise ImportError("IsccMeta.iscc_obj requires iscc-core package.")
        return Code(self.iscc)
