# generated by datamodel-codegen:
#   filename:  iscc-generator.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, Base64Str, Field, RootModel
from iscc_schema.fields import AnyUrl
from iscc_schema.base import BaseModel


class MediaUpload(BaseModel):
    """
    Media Upload
    """

    source_file: bytes | None = Field(None, description="The file used for generating the ISCC.")
    source_url: AnyUrl | None = Field(
        None,
        description="URL of file used for generating the ISCC.",
        examples=["https://picsum.photos/200/300.jpg"],
    )


class MediaID(BaseModel):
    """
    Media-ID
    """

    media_id: str | None = Field(
        None, description="Media file ID", examples=["05VJUVTH3DCP6"], max_length=13, min_length=13
    )


class MediaDownload(RootModel[bytes]):
    root: bytes = Field(
        ..., description="Media Download", examples=["string"], title="MediaDownload"
    )


class FieldType(Enum):
    """
    The type of digital content according to schema.org classes.
    """

    AudioObject = "AudioObject"
    ImageObject = "ImageObject"
    CreativeWork = "CreativeWork"
    TextDigitalDocument = "TextDigitalDocument"
    VideoObject = "VideoObject"


class Mode(Enum):
    """
    The perceptual mode used to create the ISCC-CODE.
    """

    text = "text"
    image = "image"
    audio = "audio"
    video = "video"
    mixed = "mixed"


class IsccMetadata(BaseModel):
    """
    ISCC Metadata
    """

    field_context: AnyUrl | None = Field(
        "http://purl.org/iscc/context/0.3.2.jsonld",
        alias="@context",
        description="The [JSON-LD](https://json-ld.org/) Context URI for ISCC metadata.",
    )
    field_type: FieldType | None = Field(
        None,
        alias="@type",
        description="The type of digital content according to schema.org classes.",
        examples=["ImageObject"],
    )
    field_schema: AnyUrl | None = Field(
        "http://purl.org/iscc/schema/0.3.2.json",
        alias="$schema",
        description="The [JSON Schema](https://json-schema.org/) URI of the ISCC metadata schema.",
    )
    iscc: str | None = Field(
        None,
        description="An **ISCC-CODE** in canonical representation.",
        examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"],
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    media_id: str | None = Field(
        None,
        description="Vendor specific internal identifier for media file.",
        examples=["05VJUVTH3DCP6"],
        max_length=13,
        min_length=13,
    )
    name: str | None = Field(
        None,
        description="The title or name of the intangible creation manifested by the identified *digital content*.",
        examples=["The Secret Adversary"],
        max_length=128,
    )
    description: str | None = Field(
        None,
        description="Description of the *digital content* identified by the **ISCC**.",
        examples=["A 2001 fantasy film directed by Chris Columbus and distributed by Warner Bros."],
        max_length=4096,
    )
    meta: str | None = Field(
        None,
        description="Extended metadata, wrapped in a Data-URL string.",
        examples=["data:application/json;charset=utf-8;base64,eyJleHRlbmRlZCI6Im1ldGFkYXRhIn0="],
        max_length=16384,
    )
    creator: str | None = Field(
        None,
        description="An entity primarily responsible for making the resource.",
        examples=["Agatha Christie"],
    )
    license: AnyUrl | None = Field(
        None,
        description="URL of license for the digital content.",
        examples=["https://example.com/license-terms-for-this-item"],
    )
    acquire: AnyUrl | None = Field(
        None,
        description="URL for acquiring a license for the item.",
        examples=["https://example.com/buy-this-item-here"],
    )
    mode: Mode | None = Field(
        None, description="The perceptual mode used to create the ISCC-CODE.", examples=["video"]
    )
    mediatype: str | None = Field(
        None,
        description="The [IANA Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml) (MIME type) of the referenced content.",
        examples=["image/png"],
    )
    filename: str | None = Field(
        None,
        description="Filename of the referenced **digital content** (automatically used as fallback if the `name` field was not specified for ISCC processing)",
        examples=["some-file.png"],
    )
    filesize: int | None = Field(
        None, description="File size of media asset in number of bytes.", examples=[16896]
    )
    characters: int | None = Field(
        None,
        description="Number of text characters (code points after Unicode normalization)",
        examples=[55689],
    )
    pages: int | None = Field(
        None, description="Number of pages (for paged documents only)", examples=[77]
    )
    language: str | None = Field(
        None,
        description="Main language of content [BCP 47](https://tools.ietf.org/search/bcp47).",
        examples=["en-US"],
    )
    fps: float | None = Field(None, description="Frames per second of video assets.", examples=[24])
    width: int | None = Field(
        None, description="Width of visual media in number of pixels.", examples=[640]
    )
    height: int | None = Field(
        None, description="Height of visual media in number of pixels.", examples=[480]
    )
    duration: int | None = Field(
        None, description="Duration of audio-visual media in secondes.", examples=[67]
    )
    generator: str | None = Field(
        None, description="Name and version of the software that generated the ISCC"
    )
    created: AwareDatetime | None = Field(
        None, description="Datetime the ISCC was created for the item."
    )
    metahash: str | None = Field(
        None,
        description="A [Multiformats](https://multiformats.io) multihash or IPFS CIDv1 of the ISCC seed metadata. The hash is created from `name` and `description` fields or `meta` if supplied.",
        examples=["f01551220b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"],
        min_length=40,
    )
    datahash: str | None = Field(
        None,
        description="A [Multihash](https://multiformats.io/multihash/) of the *digital content* (default blake3).",
        examples=["bdyqk6e2jxh27tingubae32rw3teutg6lexe23qisw7gjve6k4qpteyq"],
        min_length=40,
    )
    tophash: str | None = Field(
        None,
        description="A [Multihash](https://multiformats.io/multihash/) of the concatenation (binding) of metahash and datahash.",
        examples=["bdyqnosmb56tqudeibogyygmf2b25xs7wpg4zux4zcts2v6llqmnj4ja"],
        min_length=40,
    )
    thumbnail: AnyUrl | None = Field(
        None,
        description="URI for a user-presentable image that serves as a preview of the digital content. The URI may be a Data-URL RFC2397.",
        examples=["https://picsum.photos/200/300.jpg"],
    )


class NftMetadata(BaseModel):
    """
    NFT Metadata
    """

    field_context: AnyUrl | None = Field(
        None,
        alias="@context",
        description="The [JSON-LD](https://json-ld.org/) Context URI for ISCC metadata.",
        examples=["http://purl.org/iscc/context"],
    )
    field_type: FieldType | None = Field(
        None,
        alias="@type",
        description="The type of digital content according to schema.org classes.",
        examples=["ImageObject"],
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        description="The [JSON Schema](https://json-schema.org/) URI of the ISCC metadata schema.",
        examples=["http://purl.org/iscc/schema"],
    )
    iscc: str | None = Field(
        None,
        description="The **ISCC-ID** of the digital content.",
        examples=["ISCC:MEAJU5AXCPOIOYFL"],
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    name: str | None = Field(
        None,
        description="The title or name of the intangible creation manifested by the identified *digital content*.",
        examples=["The Secret Adversary"],
        max_length=128,
    )
    description: str | None = Field(
        None,
        description="Description of the *digital content* identified by the **ISCC**.",
        examples=["A 2001 fantasy film directed by Chris Columbus and distributed by Warner Bros."],
        max_length=4096,
    )
    image: AnyUrl | None = Field(
        None,
        description="URL of the actual digital content represented by the NFT or a preview of it if animation_url is provided.",
        examples=["https://picsum.photos/200/300.jpg"],
    )
    animation_url: AnyUrl | None = Field(
        None, description="URL of the actual digital content (video, audio ...)"
    )
    attributes: list[dict[str, Any]] | None = Field(
        None,
        description="Attributes of the NFT artwork. These attributes will show up on NFT marketplaces.",
        examples=[
            [
                {"trait_type": "METAL", "value": "SILVER"},
                {"display_type": "number", "trait_type": "GENERATION", "value": 1},
            ]
        ],
    )
    properties: dict[str, Any] | None = Field(
        None,
        description="Arbitrary properties. Values may be strings, numbers, object or arrays. Properties defined here may show up on NFT marketplaces. See [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155#metadata)",
    )
    external_url: AnyUrl | None = Field(
        None,
        description="This is the URL that will appear below the asset's image on some NFT Marketplaces and will allow users to leave the site and view the item on your site.",
        examples=["https://example.com/link-to-here-from-marketplace"],
    )
    license: AnyUrl | None = Field(
        None, description="URI of license for the identified digital content."
    )
    original: bool | None = Field(
        None,
        description="Whether the signee of the declaring transaction claims to be the original creator of the work manifested by the identified digital content.",
    )
    redirect: AnyUrl | None = Field(
        None,
        description="URL to which an ISCC resolver should redirect the ISCC-ID. **Supports URI template `(iscc-id)`**",
        examples=["https://example.com/redirect-here-for-iscc-id"],
    )
    verifications: list[AnyUrl] | None = Field(
        None,
        description="A list of self-verifications. Self-verifications are public URLs under the account/authority of the signee. The verification URL must respond to a GET request with text that contains a multihash of the ISCC declaration signees wallet address in the format of `verify:<multihash-of-wallet-address>:verify`.",
        examples=[["https://twitter.com/titusz/status/1490104312051257347"]],
    )


class NftPackage(BaseModel):
    """
    NFT Package
    """

    nft_id: str
    nft_metadata: NftMetadata | None = None
    nft_image: AnyUrl | None = None
    nft_animation: AnyUrl | None = None
    iscc_code: str | None = Field(
        None,
        description="An **ISCC-CODE** in canonical representation.",
        examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"],
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )


class IsccBasicMetadata(BaseModel):
    """
    Basic ISCC Metadata
    """

    name: str | None = Field(
        None,
        description="The title or name of the creation manifested by digital content.",
        examples=["The Secret Adversary"],
        max_length=128,
    )
    description: str | None = Field(
        None,
        description="Description of the digital content.",
        examples=["A 2001 fantasy film directed by Chris Columbus and distributed by Warner Bros."],
        max_length=4096,
    )
    meta: str | None = Field(
        None,
        description="Subject, industry, or use-case specific metadata. (Encoded as JSON string or Data-URL)",
        examples=["data:application/json;charset=utf-8;base64,eyJleHRlbmRlZCI6Im1ldGFkYXRhIn0="],
        max_length=16384,
    )


class TaskStatus(BaseModel):
    """
    Status of an ISCC processing task
    """

    task_id: str = Field(
        ...,
        description="Unique identifier of the task.",
        examples=["95dcc4952deb409e81d16ab7a1338648"],
    )
    started: AwareDatetime | None = Field(None, examples=["2021-01-21T17:32:28Z"])
    stopped: AwareDatetime | None = Field(None, examples=["2021-01-21T17:34:36Z"])
    success: bool | None = None
    result: str | None = Field(
        None, examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"]
    )


class Message(BaseModel):
    """
    Informational message to the client
    """

    detail: str | None = Field(
        None,
        description="Informational message about the request.",
        examples=["Either source_file or source_url must be provided."],
    )


class NftFrozen(BaseModel):
    """
    Frozen NFT
    """

    token_id_hex: str | None = Field(
        None,
        description="NFT Token-ID (uint256 encoded as hex). ",
        examples=["b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"],
    )
    token_id_num: str | None = Field(
        None,
        description="NFT Token-ID (uint256 digits as string)",
        examples=["83814198383102558219731078260892729932246618004265700685467928187377105751529"],
    )
    metadata_ipfs_uri: AnyUrl | None = Field(
        None,
        description="IPFS-URI of NFT metadata in base16 (hex) encoding. ",
        examples=[
            "ipfs://f01551220b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"
        ],
    )
    metadata_ipfs_payload: Base64Str | None = Field(
        None,
        description="JCS serialized and base64 encoded NFT metadata for publishing to IPFS",
        examples=["aGVsbG8gd29ybGQ="],
    )


class IsccExtraMetadata(BaseModel):
    """
    Additional embeddable metadata
    """

    creator: str | None = Field(
        None,
        description="An entity primarily responsible for making the resource.",
        examples=["Agatha Christie"],
    )
    license: AnyUrl | None = Field(
        None,
        description="URL of license for the digital content.",
        examples=["https://example.com/license-terms-for-this-item"],
    )
    acquire: AnyUrl | None = Field(
        None,
        description="URL for acquiring a license for the item.",
        examples=["https://example.com/buy-this-item-here"],
    )


class Chain(Enum):
    """
    The blockchain ISCC-CODE declaration.
    """

    BITCOIN = "BITCOIN"
    ETHEREUM = "ETHEREUM"
    POLYGON = "POLYGON"


class NftPostRequest(BaseModel):
    media_id_image: str = Field(
        ...,
        description="The `media_id` of the image for the NFT",
        examples=["05VJUVTH3DCP6"],
        max_length=13,
        min_length=13,
    )
    media_id_animation: str | None = Field(
        None,
        description="Optional `media_id` of an animation for the NFT",
        examples=["05VJUVTH3DCP6"],
        max_length=13,
        min_length=13,
    )
    attributes: list[dict[str, Any]] | None = Field(
        None,
        description="Similar to properties but as an array of objects. These attributes will show up on some NFT marketplaces.",
    )
    properties: dict[str, Any] | None = Field(
        None,
        description="Arbitrary properties. Values may be strings, numbers, object or arrays. Properties defined here may show up on NFT marketplaces. See [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155#metadata)",
    )
    external_url: AnyUrl | None = Field(
        None,
        description="This is the URL that will appear below the asset's image on some NFT Marketplaces and will allow users to leave the site and view the item on your site.",
    )
    chain: Chain | None = Field(
        None, description="The blockchain ISCC-CODE declaration.", examples=["POLYGON"]
    )
    wallet: str | None = Field(
        None,
        description="The wallet-address used for ISCC-CODE decleration.",
        examples=["0xb794f5ea0ba39494ce839613fffba74279579268"],
    )
    original: bool | None = Field(
        None,
        description="The signee of the declaring transaction claims to be the original creator of the work manifested by the identified digital content.",
    )
    redirect: AnyUrl | None = Field(
        None,
        description="URL to which an ISCC resolver should redirect the ISCC-ID. **Supports URI template `(iscc-id)`**",
    )
    verifications: list[AnyUrl] | None = Field(
        None,
        description="A list of self-verifications. Self-verifications are public URLs under the account/authority of the signee. The verification URL must respond to a GET request with text that contains a multihash of the ISCC declaration signees wallet address in the format of `verify:<multihash-of-wallet-address>:verify`.",
    )


class NftFreezePostRequest(BaseModel):
    """
    Any JSON object that can be serialized with JCS canonicaliztion.
    """


class MediaEmbeddedMetadata(IsccExtraMetadata, IsccBasicMetadata):
    """
    Media Metadata
    """


class IsccCodePostRequest(MediaEmbeddedMetadata, MediaUpload):
    pass
