# generated by datamodel-codegen:
#   filename:  iscc-note.yaml

from __future__ import annotations
from typing import Literal
from pydantic import ConfigDict, Field, RootModel
from iscc_schema.fields import AnyUrl
from typing import ClassVar
from iscc_schema.base import BaseModel


class Signature(BaseModel):
    """
    Cryptographic signature over the IsccNote, conforming to the [iscc-crypto](https://github.com/iscc/iscc-crypto) signing protocol. Uses EdDSA (Ed25519) with JCS canonicalization.
    """

    _default_ld: ClassVar[bool] = False
    model_config = ConfigDict(
        extra="forbid",
    )
    version: Literal["ISCC-SIG v1.0"] = Field(
        "ISCC-SIG v1.0",
        description="Signature suite version identifier.",
        examples=["ISCC-SIG v1.0"],
    )
    controller: AnyUrl | None = Field(
        None,
        description="URI identifying the key controller (e.g., a DID or CID document URL).",
        examples=["did:web:example.com"],
    )
    keyid: str | None = Field(None, description="Key identifier within the controller document.")
    pubkey: str = Field(
        ...,
        description="Ed25519 public key in multibase format (z + base58btc(0xED01 + 32-byte key)) as specified in [W3C Multikey](https://www.w3.org/TR/cid/#Multikey).",
        examples=["z6MkmeDbeC5BecFmVnTHA5PWEBaVUrGLdB3weGE2KYnXfHso"],
        max_length=48,
        min_length=48,
        pattern="^z[1-9A-HJ-NP-Za-km-z]+$",
    )
    proof: str = Field(
        ...,
        description="EdDSA signature in multibase format (z + base58btc(64-byte signature)) conforming to [eddsa-jcs-2022](https://www.w3.org/TR/vc-di-eddsa/#eddsa-jcs-2022). Base58btc encoding of a 64-byte signature ranges from 65 to 89 characters, since leading zero bytes shorten the encoding.",
        examples=[
            "z5j9nrpPw3oYSAN4XbCvk2sUtkwrueTD6V2Y35gS1KFTode2ED2YQWokPmoXw6QBYtYEFxtAQfzBhdNyr8PMwP79G"
        ],
        max_length=89,
        min_length=65,
        pattern="^z[1-9A-HJ-NP-Za-km-z]+$",
    )


class Unit(RootModel[str]):
    root: str = Field(..., max_length=73, min_length=21, pattern="^ISCC:[A-Z0-9]{16,68}$")


class IsccNote(BaseModel):
    """
    An ISCC Declaration record submitted to an ISCC-HUB for timestamping and registration. IsccNote is the permanent, self-describing log entry that binds an ISCC-CODE to its content hashes and a cryptographic signature. Stored in an append-only log, declarations are immutable once accepted, so the record is version-pinned and carries resolvable schema and context URLs.
    """

    _default_ld: ClassVar[bool] = False
    model_config = ConfigDict(
        extra="forbid",
    )
    context_: Literal["http://purl.org/iscc/context/0.7.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.7.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["IsccNote"] = Field(
        "IsccNote", alias="@type", description="The type of service metadata."
    )
    schema_: Literal["http://purl.org/iscc/schema/iscc-note-0.7.0.json"] = Field(
        "http://purl.org/iscc/schema/iscc-note-0.7.0.json",
        alias="$schema",
        description="The JSON Schema URI for ISCC Declaration metadata.",
    )
    iscc_code: str = Field(
        ...,
        description="The ISCC-CODE identifying the digital content being declared. Mapped to JSON-LD @id, making it the RDF subject of the declaration. Supports full-length 256-bit ISCC-CODEs.",
        examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"],
        max_length=73,
        min_length=34,
        pattern="^ISCC:[A-Z0-9]{29,68}$",
    )
    datahash: str = Field(
        ...,
        description="A blake3 multihash of the digital content, hex-encoded with the `1e20` multihash prefix (blake3, 32-byte digest). Binds the declaration to the exact content bytes.",
        examples=["1e20253d0f3460085c276f038de345c8e953a306f4a07f9fa77f5af8563c3d7274c5"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#datahash"},
        max_length=68,
        min_length=68,
        pattern="^1e20[0-9a-f]{64}$",
    )
    nonce: str = Field(
        ...,
        description="Cryptographic nonce for replay protection. A 128-bit random value encoded as lowercase hexadecimal.",
        examples=["0013a3c214c05796673503e6e549446d"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#nonce"},
        max_length=32,
        min_length=32,
        pattern="^[0-9a-f]{32}$",
    )
    timestamp: str | None = Field(
        None,
        description="RFC 3339 timestamp of declaration creation in UTC with millisecond precision. Optional on submission - an ISCC-HUB assigns the authoritative timestamp on receipt.",
        examples=["2025-08-12T14:30:00.123Z"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#timestamp"},
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]+)?Z$",
    )
    signature: Signature = Field(
        ...,
        description="Cryptographic signature over the IsccNote, conforming to the [iscc-crypto](https://github.com/iscc/iscc-crypto) signing protocol. Uses EdDSA (Ed25519) with JCS canonicalization.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#signature"},
    )
    units: list[Unit] | None = Field(
        None,
        description="The individual full-length ISCC-UNITs that compose the declared ISCC-CODE, enabling similarity matching against the declaration. One to four 256-bit ISCC-UNITs.",
        examples=[["ISCC:IADSKPIPGRQAQXBHN4BY3Y2FZDUVHIYG6SQH7H5HP5NPQVR4HVZHJRI"]],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#units"},
        max_length=4,
        min_length=1,
    )
    metahash: str | None = Field(
        None,
        description="A blake3 multihash of the seed metadata, hex-encoded with the `1e20` multihash prefix (blake3, 32-byte digest). Same format as `datahash`.",
        examples=["1e208bad08ad56b5517e09bc8bc5e2281b2d8f21d096939a310f539cf5007d443772"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#metahash"},
        max_length=68,
        min_length=68,
        pattern="^1e20[0-9a-f]{64}$",
    )
    gateway: str | None = Field(
        None,
        description="An HTTP(S) URL or RFC 6570 URI template of a gateway that serves metadata for the declared ISCC. Used by ISCC resolvers to discover content metadata.",
        examples=["https://gateway.example.com/declaration/{iscc_id}"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#gateway"},
        max_length=2048,
        min_length=8,
        pattern="^https?://[^\\s]+",
    )
