# generated by datamodel-codegen:
#   filename:  iscc-all.yaml

from __future__ import annotations
from enum import Enum
from pydantic import AwareDatetime, Field
from iscc_schema.fields import AnyUrl
from iscc_schema.base import BaseModel
from typing import Any


class Chain(Enum):
    """
    The blockchain on which an ISCC-CODE is declared.
    """

    PRIVATE = "PRIVATE"
    BITCOIN = "BITCOIN"
    ETHEREUM = "ETHEREUM"
    POLYGON = "POLYGON"


class IsccDeclaration(BaseModel):
    """
    Fields relevant in context with public ISCC declarations
    """

    original: bool | None = Field(
        None,
        description="The signee of the declaring transaction claims to be the original creator of the work manifested by the identified digital content.",
        examples=[True],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#original"},
    )
    redirect: AnyUrl | None = Field(
        None,
        description="URL to which an ISCC resolver should redirect the ISCC-ID. **Supports URI template `(iscc-id)`**",
        examples=["https://example.com/land-here-when-resolving-iscc-id"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#redirect"},
    )
    chain: Chain | None = Field(
        None,
        description="The blockchain on which an ISCC-CODE is declared.",
        examples=["ETHEREUM"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#chain"},
    )
    wallet: str | None = Field(
        None,
        description="The wallet-address that signs an ISCC declaration.",
        examples=["0xb794f5ea0ba39494ce839613fffba74279579268"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#wallet"},
    )
    credentials: str | dict[str, Any] | list[Any] | None = Field(
        None,
        description="One or more [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/) or one or more URIs pointing to one or more VCs. A reader of ISCC metadata must interpret the value according to the following rules <ul> <li>If the value is a JSON `string` interpret it as an URI. The expectation is that the URI dereferences to a response with Content-type `application/json` where the data is a VC or an `array` of VCs.</li><li>If the value is a JSON `object` interpret it as a VC according to the [Verifiable Credentials JSON Schema](https://w3c-ccg.github.io/vc-json-schemas/).</li><li>If the value is an `array` and an item in the `array` is a JSON `object` interpret it as a VC.</li><li>If the value is an `array` and an items is a `string` interpret the item as an URI that dereferences to VC(s)</li><li>Credentials should only be taken into account if the [`credentialSubject`](https://www.w3.org/2018/credentials/#property-definitions) matches with the declarer (e.g. [`did:pkh`](https://github.com/w3c-ccg/did-pkh/blob/main/did-pkh-method-draft.md) representation of the declarers address).</li> </ul>",
        examples=["https://schema.iscc.codes/examples/vc.json"],
        json_schema_extra={
            "x-iscc-context": "https://www.w3.org/2018/credentials#VerifiableCredential"
        },
    )
    verifications: list[dict[str, Any]] | None = Field(
        None,
        description="A list of self-verifications. Self-verifications are public URLs under the account/authority of the signee. The verification URL must respond to a GET request with text that contains a multihash of the ISCC declaration signees wallet address in the format of `verify:<multihash-of-wallet-address>:verify`.",
        examples=[[{"url": "https://twitter.com/titusz/status/1490104312051257347"}]],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#verifications"},
        max_length=128,
    )


class Signature(BaseModel):
    """
    Cryptographic signature over ISCC metadata, conforming to the [iscc-crypto](https://github.com/iscc/iscc-crypto) signing protocol. Uses EdDSA (Ed25519) with JCS canonicalization.
    """

    version: str = Field(
        ..., description="Signature suite version identifier.", examples=["ISCC-SIG v1.0"]
    )
    controller: AnyUrl | None = Field(
        None, description="URI identifying the key controller (e.g., DID or CID)."
    )
    keyid: str | None = Field(None, description="Key identifier within the controller document.")
    pubkey: str | None = Field(
        None,
        description="Ed25519 public key in multibase format (z + base58btc(0xED01 + 32-byte key)) as specified in [W3C Multikey](https://www.w3.org/TR/cid/#Multikey).",
        examples=["z6MkrJVnaZkeFzdQyMZu1cgjg7k1pZZ6pvBQ7XJPt4swbTQ2"],
        max_length=48,
        min_length=48,
        pattern="^z[1-9A-HJ-NP-Za-km-z]+$",
    )
    proof: str = Field(
        ...,
        description="EdDSA signature in multibase format (z + base58btc(64-byte signature)) conforming to [eddsa-jcs-2022](https://www.w3.org/TR/vc-di-eddsa/#eddsa-jcs-2022).",
        examples=[
            "z2HnFSSPPBzR36zdDgK8PbEHeXbR56YF24jwMpt3R1eHXQzJDMWS93FCzpvJpwTWd3GAVFuUfjoJdcnTMuVor51aX"
        ],
        max_length=89,
        min_length=89,
        pattern="^z[1-9A-HJ-NP-Za-km-z]+$",
    )


class IsccCrypto(BaseModel):
    """
    Cryptography related ISCC Metadata
    """

    tophash: str | None = Field(
        None,
        description="A [Multihash](https://multiformats.io/multihash/) of the concatenation (binding) of metahash and datahash (default blake3).",
        examples=["bdyqnosmb56tqudeibogyygmf2b25xs7wpg4zux4zcts2v6llqmnj4ja"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#tophash"},
        min_length=40,
    )
    metahash: str | None = Field(
        None,
        description="A [Multiformats](https://multiformats.io) multihash or IPFS CIDv1 of the supplied metadata. The hash is created from `name` and `description` fields or `meta` if supplied.",
        examples=["f01551220b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#metahash"},
        min_length=40,
    )
    datahash: str | None = Field(
        None,
        description="A [Multihash](https://multiformats.io/multihash/) of the *digital content* (default blake3).",
        examples=["bdyqk6e2jxh27tingubae32rw3teutg6lexe23qisw7gjve6k4qpteyq"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#datahash"},
        min_length=40,
    )
    nonce: str | None = Field(
        None,
        description="Cryptographic nonce for replay protection. A 128-bit random value encoded as lowercase hexadecimal.",
        examples=["0013a3c214c05796673503e6e549446d"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#nonce"},
        max_length=32,
        min_length=32,
        pattern="^[0-9a-f]{32}$",
    )
    signature: Signature | None = Field(
        None,
        description="Cryptographic signature over ISCC metadata, conforming to the [iscc-crypto](https://github.com/iscc/iscc-crypto) signing protocol. Uses EdDSA (Ed25519) with JCS canonicalization.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#signature"},
    )


class IsccNft(BaseModel):
    """
    Metadata for NFT Marketplaces
    """

    external_url: AnyUrl | None = Field(
        None,
        description="This is the URL that will appear below the asset's image on some NFT Marketplaces and will allow users to leave the site and view the item on your site. **Supports URI template `(iscc-id)`**.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#external_url"},
    )
    animation_url: AnyUrl | None = Field(
        None,
        description="A URL to a multi-media attachment for the item.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#animation_url"},
    )
    properties: dict[str, Any] | None = Field(
        None,
        description="Arbitrary properties. Values may be strings, numbers, object or arrays. Properties defined here may show up on NFT marketplaces. See [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155#metadata)",
        examples=[
            {
                "simple_property": "example value",
                "rich_property": {
                    "name": "Name",
                    "value": "123",
                    "display_value": "123 Example Value",
                    "class": "emphasis",
                    "css": {
                        "color": "#ffffff",
                        "font-weight": "bold",
                        "text-decoration": "underline",
                    },
                },
                "array_property": {"name": "Name", "value": [1, 2, 3, 4], "class": "emphasis"},
            }
        ],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#properties"},
    )
    attributes: list[dict[str, Any]] | None = Field(
        None,
        description="Similar to `properties` but as an array of objects. These attributes will show up on some NFT marketplaces.",
        examples=[
            [
                {"trait_type": "METAL", "value": "SILVER"},
                {"display_type": "number", "trait_type": "GENERATION", "value": 1},
            ]
        ],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#attributes"},
    )
    nft: AnyUrl | None = Field(
        None,
        description="A unique URI for a non-fungible token of the identified content. The URI must contain references to the blockchain, smart-contract and token. The recommended schemes are [CAIP-22](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-22.md) and [CAIP-29](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-29.md).",
        examples=["eip155:1/erc721:0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/771769"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#nft"},
    )


class Mode(Enum):
    """
    The perceptual mode used to create the ISCC-CODE.
    """

    text = "text"
    image = "image"
    audio = "audio"
    video = "video"
    mixed = "mixed"


class IsccTechnical(BaseModel):
    """
    Technical ISCC Metadata automatically inferred from the *digital content* by an ISCC Processor
    """

    mode: Mode | None = Field(
        None,
        description="The perceptual mode used to create the ISCC-CODE.",
        examples=["video"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#mode"},
    )
    created: AwareDatetime | None = Field(
        None,
        description="Datetime the ISCC was created for the item.",
        json_schema_extra={"x-iscc-context": "http://schema.org/dateCreated"},
    )
    filename: str | None = Field(
        None,
        description="Filename of the referenced **digital content** (automatically used as fallback if the `name` field was not specified for ISCC processing)",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#filename"},
    )
    filesize: int | None = Field(
        None,
        description="File size of media asset in number of bytes.",
        json_schema_extra={"x-iscc-context": "http://schema.org/fileSize"},
    )
    mediatype: str | None = Field(
        None,
        description="An [IANA Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml) (MIME type)",
        examples=["image/png"],
        json_schema_extra={"x-iscc-context": "http://schema.org/encodingFormat"},
    )
    duration: int | None = Field(
        None,
        description="Duration of audio-visual media in seconds.",
        json_schema_extra={"x-iscc-context": "http://schema.org/duration"},
    )
    fps: float | None = Field(
        None,
        description="Frames per second of video assets.",
        examples=[24],
        ge=1.0,
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#fps"},
    )
    width: int | None = Field(
        None,
        description="Width of visual media in number of pixels.",
        examples=[640],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#width"},
    )
    height: int | None = Field(
        None,
        description="Height of visual media in number of pixels.",
        examples=[480],
        ge=1,
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#height"},
    )
    characters: int | None = Field(
        None,
        description="Number of text characters (code points after Unicode normalization)",
        examples=[55689],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#characters"},
    )
    pages: int | None = Field(
        None,
        description="Number of pages (for paged documents only)",
        examples=[77],
        json_schema_extra={"x-iscc-context": "http://schema.org/numberOfPages"},
    )
    language: str | list[str] | None = Field(
        None,
        description="Language(s) of content [BCP 47](https://tools.ietf.org/search/bcp47).",
        examples=["en-US"],
        json_schema_extra={"x-iscc-context": "http://schema.org/inLanguage"},
    )
    parts: list[str | dict[str, Any]] | None = Field(
        None,
        description="Indicates items that are part of this item via Content-Codes (inverse-property belongs).",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#parts"},
    )
    part_of: list[str] | None = Field(
        None,
        description="Indicates that this item is part of other items via their Content-Code.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#part_of"},
    )
    features: list[dict[str, Any]] | None = Field(
        None,
        description="Granular features of the *digital content*.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#features"},
    )
    units: list[str] | None = Field(
        None,
        description="Individual ISCC-UNITs that make up a composite ISCC-CODE.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#units"},
    )
    generator: str | None = Field(
        None,
        description="Name and version of the software that generated the ISCC",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#generator"},
    )
    text: str | None = Field(
        None,
        description="Extracted plaintext of the *digital content*.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#text"},
    )
    thumbnail: AnyUrl | None = Field(
        None,
        description="URI of an autogenerated user-presentable thumbnail-image that serves as a preview of the digital content. The URI may be a Data-URL RFC2397.",
        examples=["https://picsum.photos/200/300.jpg"],
        json_schema_extra={"x-iscc-context": "http://schema.org/thumbnailUrl"},
    )


class IsccExtended(BaseModel):
    """
    Extended ISCC Metadata
    """

    media_id: str | None = Field(
        None,
        description="Vendor specific (internal) identifier for the source media file.",
        examples=["05VQ3BGTGFCJA"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#media_id"},
    )
    iscc_id: str | None = Field(
        None,
        description="The **ISCC-ID** of the digital content in canonical representation. A valid ISCC Metadata object should include at least one of the `iscc`, `iscc_id`, or `iscc_code` fields.",
        examples=["ISCC:MAACAJINXFXA2SQX"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#iscc_id"},
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    iscc_code: str | None = Field(
        None,
        description="A composite **ISCC-CODE** in canonical representation. Explicit alternative to the more compact `iscc` field. A valid ISCC Metadata object should include at least one of the `iscc`, `iscc_id`, or `iscc_code` fields.",
        examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#iscc"},
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    image: AnyUrl | None = Field(
        None,
        description="URI for a user-presentable image that serves as a preview of the *digital content*. The URI may be a Data-URL [RFC2397](https://datatracker.ietf.org/doc/html/rfc2397). If **ISCC** metadata is used as NFT metadata according to [ERC-721](https://ethereum.org/en/developers/docs/standards/tokens/erc-721/) or [ERC-1155](https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/) the URI should reference the actual digital content represented by the NFT.",
        examples=["https://picsum.photos/200/300.jpg"],
        json_schema_extra={"x-iscc-context": "http://schema.org/image"},
    )
    identifier: str | list[str] | None = Field(
        None,
        description="Other identifier(s) referencing the work, product or other abstraction of which the referenced **digital content** is a full or partial manifestation.",
        json_schema_extra={"x-iscc-context": "http://schema.org/identifier"},
    )
    content: AnyUrl | None = Field(
        None,
        description="URI of the *digital content* that was used to create this ISCC.",
        json_schema_extra={"x-iscc-context": "http://schema.org/contentUrl"},
    )
    keywords: str | list[str] | None = Field(
        None,
        description="Keywords or tags used to describe this content. Either a list of keywords or a string with comma separated keywords.",
        json_schema_extra={"x-iscc-context": "http://schema.org/keywords"},
    )
    previous: str | None = Field(
        None,
        description="ISCC of the preceding version of this item.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#previous"},
    )
    version: int | str | None = Field(
        None,
        description="The version of the CreativeWork embodied by a specified resource.",
        json_schema_extra={"x-iscc-context": "http://schema.org/version"},
    )


class IsccEmbeddable(BaseModel):
    """
    Metadata intended to be embedded into the media asset.
    """

    creator: str | list[str] | None = Field(
        None,
        description="An entity primarily responsible for making the resource.",
        examples=["Agatha Christie"],
        json_schema_extra={"x-iscc-context": "http://schema.org/creator"},
    )
    license: AnyUrl | None = Field(
        None,
        description="URI of license for the identified *digital content*.",
        examples=["https://example.com/license-terms-for-this-item"],
        json_schema_extra={"x-iscc-context": "http://schema.org/license"},
    )
    acquire: AnyUrl | None = Field(
        None,
        description="This field must contain a valid URL referring to a page showing information about how one can acquire a license for the item. This may be a page of a web shop or NFT marketplace ready for providing a license.",
        examples=["https://example.com/buy-license-for-item-here"],
        json_schema_extra={"x-iscc-context": "http://schema.org/acquireLicensePage"},
    )
    credit: str | None = Field(
        None,
        description="A line of text that you expect users of the image (such as Google Images) to display alongside the image.",
        examples=["Frank Farian - Getty Images"],
        json_schema_extra={"x-iscc-context": "http://schema.org/creditText"},
    )
    rights: str | None = Field(
        None,
        description="Contains any necessary copyright notice and should identify the current owner of the copyright of this work with associated intellectual property rights.",
        examples=["© Copyright 2022 ISCC Foundation - www.iscc.codes"],
        json_schema_extra={"x-iscc-context": "http://schema.org/copyrightNotice"},
    )


class IsccBasic(BaseModel):
    """
    Basic user presentable ISCC Metadata essential for Meta-Code and Meta-Hash generation.
    """

    name: str | None = Field(
        None,
        description="The title or name of the intangible creation manifested by the identified *digital content*. **Used as input for ISCC Meta-Code generation**.",
        examples=["The Never Ending Story"],
        json_schema_extra={"x-iscc-context": "http://schema.org/name"},
        max_length=128,
        min_length=1,
    )
    description: str | None = Field(
        None,
        description="Description of the *digital content* identified by the **ISCC**. **Used as input for ISCC Meta-Code generation**. Any user presentable text string (including Markdown text) indicative of the identity  of the referent may be used.",
        examples=["a 1984 fantasy film co-written and directed by *Wolfgang Petersen*"],
        json_schema_extra={"x-iscc-context": "http://schema.org/disambiguatingDescription"},
        max_length=4096,
        min_length=1,
    )
    meta: str | None = Field(
        None,
        description="Subject, industry, or use-case specific metadata encoded as Data-URL.",
        examples=["data:application/json;charset=utf-8;base64,eyJleHRlbmRlZCI6Im1ldGFkYXRhIn0="],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#meta"},
        max_length=16384,
    )


class IsccMinimal(BaseModel):
    """
    Minimal required ISCC Metadata
    """

    iscc: str | None = Field(
        None,
        description="An **ISCC-CODE** in canonical representation. A valid ISCC Metadata object should include at least one of the `iscc`, `iscc_id`, or `iscc_code` fields.",
        examples=["ISCC:KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#iscc"},
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )


class Type(Enum):
    """
    The type of digital content according to schema.org classes (TextDigitalDocument, ImageObject, AudioObject, VideoObject).
    """

    CreativeWork = "CreativeWork"
    TextDigitalDocument = "TextDigitalDocument"
    ImageObject = "ImageObject"
    AudioObject = "AudioObject"
    VideoObject = "VideoObject"


class IsccJsonld(BaseModel):
    """
    The ISCC [JSON-LD](https://json-ld.org/) Context and [JSON Schema](https://json-schema.org/) reference
    """

    context_: AnyUrl | None = Field(
        "http://purl.org/iscc/context",
        alias="@context",
        description="The [JSON-LD](https://json-ld.org/) Context URI for ISCC metadata.",
    )
    type_: Type | None = Field(
        "CreativeWork",
        alias="@type",
        description="The type of digital content according to schema.org classes (TextDigitalDocument, ImageObject, AudioObject, VideoObject).",
    )
    schema_: AnyUrl | None = Field(
        "http://purl.org/iscc/schema",
        alias="$schema",
        description="The [JSON Schema](https://json-schema.org/) URI for ISCC metadata.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#$schema"},
    )


class IsccMeta(
    IsccDeclaration,
    IsccCrypto,
    IsccNft,
    IsccTechnical,
    IsccExtended,
    IsccEmbeddable,
    IsccBasic,
    IsccMinimal,
    IsccJsonld,
):
    """
    ISCC Metadata Schema
    """
