# generated by datamodel-codegen:
#   filename:  stm.yaml

from __future__ import annotations
from enum import Enum
from typing import Literal
from pydantic import Field
from typing import ClassVar
from iscc_schema.base import BaseModel


class ResourceType(Enum):
    """
    The kind of research output as a readable token. Tokens follow the DataCite resource-type vocabulary and are populated from the Crossref/DataCite work type (for example, journal-article maps to JournalArticle). Each token is mapped to a resolvable schema.org or FaBiO class IRI in the JSON-LD context (see x-iscc-enum-context). This is the work-kind axis; version_type is the orthogonal version-stage axis.
    """

    JournalArticle = "JournalArticle"
    Preprint = "Preprint"
    ConferencePaper = "ConferencePaper"
    ReviewArticle = "ReviewArticle"
    BookChapter = "BookChapter"
    Book = "Book"
    Dissertation = "Dissertation"
    Report = "Report"
    ReferenceEntry = "ReferenceEntry"
    Dataset = "Dataset"
    Software = "Software"
    Model = "Model"
    Workflow = "Workflow"
    Protocol = "Protocol"
    Image = "Image"
    PeerReview = "PeerReview"
    Other = "Other"


class VersionType(Enum):
    """
    Manifestation version using the NISO JAV (RP-8-2008) vocabulary. Publisher-specific version taxonomies are mapped into these values. Lets a Version-of-Record and an Accepted-Manuscript of the same work produce different Meta-Codes while a shared work-level `doi` links them.
    """

    AO = "AO"
    SMUR = "SMUR"
    AM = "AM"
    P = "P"
    VoR = "VoR"
    CVoR = "CVoR"
    EVoR = "EVoR"


class STM(BaseModel):
    """
    STM (Scientific/Technical/Medical) Seed Metadata for interoperable Meta-Code generation. Minimal distinguishing metadata for scholarly works identified by a DOI, populatable from any DOI via Crossref/DataCite content negotiation (CSL-JSON).
    """

    _default_ld: ClassVar[bool] = False
    context_: Literal["http://purl.org/iscc/context/0.7.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.7.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["STM"] = Field("STM", alias="@type", description="The type of seed metadata.")
    schema_: Literal["http://purl.org/iscc/schema/stm-0.7.0.json"] = Field(
        "http://purl.org/iscc/schema/stm-0.7.0.json",
        alias="$schema",
        description="The JSON Schema URI for STM seed metadata.",
    )
    doi: str = Field(
        ...,
        description="Digital Object Identifier of the work, lowercased, in bare prefix form (without the https://doi.org/ resolver prefix).",
        examples=["10.1016/j.jnt.2020.04.008"],
        json_schema_extra={"x-iscc-context": "http://purl.org/ontology/bibo/doi"},
        pattern="^10\\.\\d{4,}/.+$",
    )
    resource_type: ResourceType = Field(
        ...,
        description="The kind of research output as a readable token. Tokens follow the DataCite resource-type vocabulary and are populated from the Crossref/DataCite work type (for example, journal-article maps to JournalArticle). Each token is mapped to a resolvable schema.org or FaBiO class IRI in the JSON-LD context (see x-iscc-enum-context). This is the work-kind axis; version_type is the orthogonal version-stage axis.",
        examples=["JournalArticle"],
        json_schema_extra={"x-iscc-context": "http://schema.org/additionalType"},
    )
    title: str = Field(
        ...,
        description="The primary title of the work.",
        examples=["Twisting moduli for GL(2)"],
        json_schema_extra={"x-iscc-context": "http://schema.org/name"},
        max_length=128,
    )
    publisher: str = Field(
        ...,
        description="Name of the publishing entity.",
        examples=["Elsevier Inc."],
        json_schema_extra={"x-iscc-context": "http://schema.org/publisher"},
        max_length=100,
    )
    pubyear: int = Field(
        ...,
        description="Year of publication. Crossref guarantees year-level precision only; using an integer avoids the false precision of a full date.",
        examples=[2020],
        ge=1000,
        json_schema_extra={"x-iscc-context": "http://schema.org/datePublished"},
        le=9999,
    )
    version_type: VersionType | None = Field(
        None,
        description="Manifestation version using the NISO JAV (RP-8-2008) vocabulary. Publisher-specific version taxonomies are mapped into these values. Lets a Version-of-Record and an Accepted-Manuscript of the same work produce different Meta-Codes while a shared work-level `doi` links them.",
        examples=["VoR"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#version_type"},
    )
    version_doi: str | None = Field(
        None,
        description="DOI assigned to this specific version, where one exists.",
        examples=["10.1016/j.jnt.2020.04.008"],
        json_schema_extra={"x-iscc-context": "http://purl.org/ontology/bibo/doi"},
        pattern="^10\\.\\d{4,}/.+$",
    )
    container_title: str | None = Field(
        None,
        description="Title of the serial or collection the work is part of (journal, proceedings, book). Not guaranteed for standalone works.",
        examples=["Journal of Number Theory"],
        json_schema_extra={
            "x-iscc-context": "http://prismstandard.org/namespaces/basic/2.0/publicationName"
        },
        max_length=200,
    )
    issn: str | None = Field(
        None,
        description="ISSN of the container serial. Only present for serial publications.",
        examples=["0022-314X"],
        json_schema_extra={"x-iscc-context": "http://schema.org/issn"},
        pattern="^\\d{4}-\\d{3}[\\dxX]$",
    )
    creator: str | None = Field(
        None,
        description="Family name of the first listed creator, normalized. Optional; the most stable cross-catalog author token.",
        examples=["Booker"],
        json_schema_extra={"x-iscc-context": "http://schema.org/creator"},
        max_length=100,
    )
