# generated by datamodel-codegen:
#   filename:  isrc.yaml

from __future__ import annotations
from enum import Enum
from typing import Literal
from pydantic import Field
from iscc_schema.base import BaseModel


class ContentType(Enum):
    """
    Indicates whether the recording is a sound recording or music video recording.
    """

    sound = "sound"
    video = "video"


class ISRC(BaseModel):
    """
    ISRC Seed Metadata for interoperable Meta-Code generation.
    """

    context_: Literal["http://purl.org/iscc/context"] = Field(
        "http://purl.org/iscc/context",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["ISRC"] = Field("ISRC", alias="@type", description="The type of seed metadata.")
    schema_: Literal["http://purl.org/iscc/schema/isrc.json"] = Field(
        "http://purl.org/iscc/schema/isrc.json",
        alias="$schema",
        description="The JSON Schema URI for ISRC seed metadata.",
    )
    isrc: str = Field(
        ...,
        description="The International Standard Recording Code assigned to this recording.",
        examples=["AA6Q72000047"],
        json_schema_extra={"x-iscc-context": "http://schema.org/isrcCode"},
        pattern="^[A-Z]{2}-?\\w{3}-?\\d{2}-?\\d{5}$",
    )
    main_artist: str = Field(
        ...,
        description="The name of the featured artist or band.",
        examples=["The Beatles"],
        json_schema_extra={"x-iscc-context": "http://schema.org/byArtist"},
        max_length=100,
    )
    track_title: str = Field(
        ...,
        description="The title of the recording.",
        examples=["Yesterday"],
        json_schema_extra={"x-iscc-context": "http://schema.org/name"},
        max_length=100,
    )
    version_title: str = Field(
        ...,
        description="Additional information about the recording, such as 'live' or 'remastered'.",
        examples=["Remastered 2009"],
        json_schema_extra={"x-iscc-context": "http://schema.org/alternativeHeadline"},
        max_length=100,
    )
    duration: int = Field(
        ...,
        description="The elapsed playing time of the recording in seconds.",
        examples=[125],
        json_schema_extra={"x-iscc-context": "http://schema.org/duration"},
    )
    content_type: ContentType = Field(
        ...,
        description="Indicates whether the recording is a sound recording or music video recording.",
        examples=["sound"],
    )
    pubdate: str = Field(
        ...,
        description="The date of first publication of the recording in ISO 8601 basic format (YYYYMMDD).",
        examples=["20090909"],
        json_schema_extra={"x-iscc-context": "http://schema.org/datePublished"},
        pattern="^\\d{8}$",
    )
