# generated by datamodel-codegen:
#   filename:  isbn.yaml

from __future__ import annotations
from typing import Literal
from pydantic import Field
from iscc_schema.base import BaseModel


class ISBN(BaseModel):
    """
    ISBN Seed Metadata for interoperable Meta-Code generation.
    """

    context_: Literal["http://purl.org/iscc/context/0.5.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.5.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["ISBN"] = Field("ISBN", alias="@type", description="The type of seed metadata.")
    schema_: Literal["http://purl.org/iscc/schema/isbn.json"] = Field(
        "http://purl.org/iscc/schema/isbn.json",
        alias="$schema",
        description="The JSON Schema URI for ISBN seed metadata.",
    )
    isbn: str = Field(
        ...,
        description="International Standard Book Number in 13-digit format, without spaces or hyphens.",
        examples=["9789295055124"],
        json_schema_extra={"x-iscc-context": "http://schema.org/isbn"},
        pattern="^\\d{13}$",
    )
    productform: str = Field(
        ...,
        description="Product form code indicating the medium and format of the publication (ONIX codelist 150).",
        examples=["EA"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#productform"},
        max_length=2,
        min_length=2,
    )
    title: str = Field(
        ...,
        description="The title of the publication.",
        examples=["The Never Ending Story"],
        json_schema_extra={"x-iscc-context": "http://schema.org/name"},
        max_length=128,
    )
    language: str = Field(
        ...,
        description="ISO 639-2/B three-letter language code.",
        examples=["eng"],
        json_schema_extra={"x-iscc-context": "http://schema.org/inLanguage"},
        pattern="^[a-z]{3}$",
    )
    imprint: str = Field(
        ...,
        description="The brand name under which the publication is published.",
        examples=["Penguin Classics"],
        json_schema_extra={"x-iscc-context": "http://schema.org/publisherImprint"},
        max_length=100,
    )
    publisher: str = Field(
        ...,
        description="The person or organization that owns the imprint at the date of publication.",
        examples=["Penguin Random House"],
        json_schema_extra={"x-iscc-context": "http://schema.org/publisher"},
        max_length=100,
    )
    country: str = Field(
        ...,
        description="Country of publication in accordance with ISO 3166-1 alpha-2 country codes.",
        examples=["US"],
        json_schema_extra={"x-iscc-context": "http://schema.org/countryOfOrigin"},
        pattern="^[A-Z]{2}$",
    )
    pubdate: str = Field(
        ...,
        description="The date of first publication under this ISBN in ISO 8601 basic format (YYYYMMDD).",
        examples=["20240214"],
        json_schema_extra={"x-iscc-context": "http://schema.org/datePublished"},
        pattern="^\\d{8}$",
    )
