# generated by datamodel-codegen:
#   filename:  tdm.yaml

from __future__ import annotations
from enum import Enum
from typing import Literal
from pydantic import ConfigDict, Field
from iscc_schema.base import BaseModel


class Train(Enum):
    """
    TDM reservation status for AI model training. Covers pre-training, fine-tuning, RLHF, distillation, and embedding training.
    """

    reserved = "reserved"
    open = "open"


class Inference(Enum):
    """
    TDM reservation status for inference-time content retrieval. Covers RAG, grounding, fact-checking, and context augmentation.
    """

    reserved = "reserved"
    open = "open"


class Derive(Enum):
    """
    TDM reservation status for AI-assisted content transformation. Covers summarization, translation, format adaptation, and content reformulation.
    """

    reserved = "reserved"
    open = "open"


class Search(Enum):
    """
    TDM reservation status for search and discovery indexing. Covers content indexing with title, snippet, and source attribution.
    """

    reserved = "reserved"
    open = "open"


class Analyze(Enum):
    """
    TDM reservation status for automated content analysis. Covers classification, sentiment analysis, topic modeling, and metadata extraction.
    """

    reserved = "reserved"
    open = "open"


class TDM(BaseModel):
    """
    Machine-readable TDM reservation signals for AI-related content usage categories. A 'reserved' status indicates an explicit opt-out from TDM exceptions (e.g., EU DSM Directive Art. 4). An 'open' status indicates that no rights are reserved. Omitted fields indicate that the reservation status has not been determined. These signals are designed for use within content identification and discovery protocols that provide additional identity, provenance, and trust context.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    context_: Literal["http://purl.org/iscc/context"] = Field(
        "http://purl.org/iscc/context",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["TDM"] = Field("TDM", alias="@type", description="The type of service metadata.")
    schema_: Literal["http://purl.org/iscc/schema/tdm.json"] = Field(
        "http://purl.org/iscc/schema/tdm.json",
        alias="$schema",
        description="The JSON Schema URI for TDM service metadata.",
    )
    train: Train | None = Field(
        None,
        description="TDM reservation status for AI model training. Covers pre-training, fine-tuning, RLHF, distillation, and embedding training.",
        examples=["reserved"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#train"},
    )
    inference: Inference | None = Field(
        None,
        description="TDM reservation status for inference-time content retrieval. Covers RAG, grounding, fact-checking, and context augmentation.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#inference"},
    )
    derive: Derive | None = Field(
        None,
        description="TDM reservation status for AI-assisted content transformation. Covers summarization, translation, format adaptation, and content reformulation.",
        examples=["reserved"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#derive"},
    )
    search: Search | None = Field(
        None,
        description="TDM reservation status for search and discovery indexing. Covers content indexing with title, snippet, and source attribution.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#search"},
    )
    analyze: Analyze | None = Field(
        None,
        description="TDM reservation status for automated content analysis. Covers classification, sentiment analysis, topic modeling, and metadata extraction.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#analyze"},
    )
