# generated by datamodel-codegen:
#   filename:  tdm.yaml

from __future__ import annotations
from enum import Enum
from typing import Literal
from pydantic import Field
from iscc_schema.base import BaseModel


class Train(Enum):
    """
    Reservation status for AI model training. Covers pre-training, fine-tuning, RLHF, distillation, and embedding training.
    """

    reserved = "reserved"
    open = "open"


class Inference(Enum):
    """
    Reservation status for inference-time content retrieval. Covers RAG, grounding, fact-checking, and context augmentation.
    """

    reserved = "reserved"
    open = "open"


class Derive(Enum):
    """
    Reservation status for AI-generated derivative works. Covers summarization, translation, format adaptation, and content reformulation.
    """

    reserved = "reserved"
    open = "open"


class Search(Enum):
    """
    Reservation status for search and discovery indexing. Covers content indexing with title, snippet, and source attribution.
    """

    reserved = "reserved"
    open = "open"


class Analyze(Enum):
    """
    Reservation status for automated content analysis. Covers classification, sentiment analysis, topic modeling, and metadata extraction.
    """

    reserved = "reserved"
    open = "open"


class TDM(BaseModel):
    """
    Text and Data Mining reservation metadata for AI content usage rights.
    """

    context_: Literal["http://purl.org/iscc/context"] = Field(
        "http://purl.org/iscc/context",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["TDM"] = Field("TDM", alias="@type", description="The type of service metadata.")
    schema_: Literal["http://purl.org/iscc/schema/tdm.json"] = Field(
        "http://purl.org/iscc/schema/tdm.json",
        alias="$schema",
        description="The JSON Schema URI for TDM service metadata.",
    )
    train: Train = Field(
        ...,
        description="Reservation status for AI model training. Covers pre-training, fine-tuning, RLHF, distillation, and embedding training.",
        examples=["reserved"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#train"},
    )
    inference: Inference = Field(
        ...,
        description="Reservation status for inference-time content retrieval. Covers RAG, grounding, fact-checking, and context augmentation.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#inference"},
    )
    derive: Derive = Field(
        ...,
        description="Reservation status for AI-generated derivative works. Covers summarization, translation, format adaptation, and content reformulation.",
        examples=["reserved"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#derive"},
    )
    search: Search = Field(
        ...,
        description="Reservation status for search and discovery indexing. Covers content indexing with title, snippet, and source attribution.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#search"},
    )
    analyze: Analyze = Field(
        ...,
        description="Reservation status for automated content analysis. Covers classification, sentiment analysis, topic modeling, and metadata extraction.",
        examples=["open"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#analyze"},
    )
