# generated by datamodel-codegen:
#   filename:  genai.yaml

from __future__ import annotations
from enum import Enum
from typing import Literal
from pydantic import ConfigDict, Field
from iscc_schema.fields import AnyUrl
from iscc_schema.base import BaseModel


class Involvement(Enum):
    """
    Level of generative AI involvement in content creation. 'human' indicates content created purely by human effort without generative AI. 'ai_assisted' indicates content created by human effort with support from generative AI. 'human_supervised' indicates content created by generative AI but supervised or reviewed by humans. 'ai_generated' indicates content created by generative AI without human supervision.
    """

    human = "human"
    ai_assisted = "ai_assisted"
    human_supervised = "human_supervised"
    ai_generated = "ai_generated"


class GenAI(BaseModel):
    """
    Machine-readable generative AI disclosure signals for content transparency. Designed for AI providers to declare the level of AI involvement in content creation, supporting compliance with transparency regulations (e.g., EU AI Act Art. 50) and enabling end users to verify AI-generated content. These signals are designed for use within content identification and discovery protocols that provide additional identity, provenance, and trust context.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    context_: Literal["http://purl.org/iscc/context/0.5.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.5.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["GenAI"] = Field(
        "GenAI", alias="@type", description="The type of service metadata."
    )
    schema_: Literal["http://purl.org/iscc/schema/genai.json"] = Field(
        "http://purl.org/iscc/schema/genai.json",
        alias="$schema",
        description="The JSON Schema URI for GenAI service metadata.",
    )
    involvement: Involvement | None = Field(
        None,
        description="Level of generative AI involvement in content creation. 'human' indicates content created purely by human effort without generative AI. 'ai_assisted' indicates content created by human effort with support from generative AI. 'human_supervised' indicates content created by generative AI but supervised or reviewed by humans. 'ai_generated' indicates content created by generative AI without human supervision.",
        examples=["ai_generated"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#involvement"},
    )
    ai_system: str | None = Field(
        None,
        description="Name or identifier of the generative AI system used for content creation. Aligns with IPTC Photo Metadata 2025.1 'AI System Used' property.",
        examples=["DALL-E 3"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#ai_system"},
        max_length=256,
    )
    digital_source_type: AnyUrl | None = Field(
        None,
        description="IPTC Digital Source Type URI for granular content source classification. This optional field bridges to the IPTC controlled vocabulary, an external evolving standard that offers finer-grained source type distinctions than the 'involvement' field. Also used by C2PA Content Credentials. See https://cv.iptc.org/newscodes/digitalsourcetype/",
        examples=["http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"],
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#digital_source_type"},
    )
