# generated by datamodel-codegen:
#   filename:  identifiers.yaml

from __future__ import annotations
from pydantic import ConfigDict, Field
from iscc_schema.base import BaseModel
from typing import Literal


class Identifier(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    scheme: str = Field(
        ...,
        description="Lowercase token naming the identifier namespace, such as doi, isrc, iswc, isbn, issn, ror, or orcid.",
        json_schema_extra={"x-iscc-context": "http://schema.org/propertyID"},
        min_length=1,
        pattern="^[a-z0-9]+([._-][a-z0-9]+)*$",
    )
    code: str = Field(
        ...,
        description="Identifier value within the declared scheme, normalized by the producer according to the scheme's conventions.",
        json_schema_extra={"x-iscc-context": "http://schema.org/value"},
        min_length=1,
    )
    scope: str | None = Field(
        None,
        description="Optional lowercase token naming the level the identifier applies to, such as work, series, manifestation, asset, organization, or person.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#scope"},
        pattern="^[a-z0-9]+([._-][a-z0-9]+)*$",
    )
    primary: bool | None = Field(
        None,
        description="Preferred identifier flag within the same scope. True means preferred; false is equivalent to omission and is normalized away by the model construction path.",
        json_schema_extra={"x-iscc-context": "http://purl.org/iscc/terms/#primary"},
    )


class Identifiers(BaseModel):
    """
    Set of typed external identifiers served for an asset identified by an ISCC.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    context_: Literal["http://purl.org/iscc/context/0.8.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.8.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["Identifiers"] = Field(
        "Identifiers", alias="@type", description="The type of service metadata."
    )
    schema_: Literal["http://purl.org/iscc/schema/identifiers-0.8.0.json"] = Field(
        "http://purl.org/iscc/schema/identifiers-0.8.0.json",
        alias="$schema",
        description="The JSON Schema URI for Identifiers service metadata.",
    )
    iscc: str | None = Field(
        None,
        description="An ISCC-CODE or ISCC-ID identifying the digital content these identifiers apply to. Mapped to JSON-LD @id when present; when omitted, the serving transport must preserve the asset subject out of band.",
        examples=["ISCC:MAACAJINXFXA2SQX"],
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    identifier: list[Identifier] = Field(
        ...,
        description="One or more typed external identifiers associated with the asset.",
        json_schema_extra={"x-iscc-context": "http://schema.org/identifier"},
        min_length=1,
    )
