# generated by datamodel-codegen:
#   filename:  tdm.yaml

from __future__ import annotations
from enum import IntEnum
from typing import Literal
from pydantic import ConfigDict, Field
from iscc_schema.fields import AnyUrl
from typing import ClassVar
from iscc_schema.base import BaseModel


class TdmReservation(IntEnum):
    """
    Blanket TDM reservation flag, semantically equivalent to W3C TDMRep tdm-reservation. 1 = rights reserved (EU DSM Art. 4 opt-out), 0 = not reserved, absent = undeclared.
    """

    integer_0 = 0
    integer_1 = 1


class TDM(BaseModel):
    """
    Machine-readable TDM rights signals conformant with W3C TDMRep, providing content-addressed delivery of tdm-reservation and tdm-policy properties via ISCC. Designed for content identification and discovery where identity, provenance, and trust context complement the reservation signal.
    """

    _default_ld: ClassVar[bool] = False
    model_config = ConfigDict(
        extra="allow",
    )
    context_: Literal["http://purl.org/iscc/context/0.6.0.jsonld"] = Field(
        "http://purl.org/iscc/context/0.6.0.jsonld",
        alias="@context",
        description="The JSON-LD Context URI for ISCC metadata.",
    )
    type_: Literal["TDM"] = Field("TDM", alias="@type", description="The type of service metadata.")
    schema_: Literal["http://purl.org/iscc/schema/tdm.json"] = Field(
        "http://purl.org/iscc/schema/tdm.json",
        alias="$schema",
        description="The JSON Schema URI for TDM service metadata.",
    )
    iscc: str | None = Field(
        None,
        description="An ISCC-CODE or ISCC-ID identifying the digital content this TDM declaration applies to. Mapped to JSON-LD @id, making it the RDF subject of the declaration.",
        examples=["ISCC:MAACAJINXFXA2SQX"],
        max_length=73,
        min_length=15,
        pattern="^ISCC:[A-Z2-7]{10,73}$",
    )
    tdm_reservation: TdmReservation | None = Field(
        None,
        description="Blanket TDM reservation flag, semantically equivalent to W3C TDMRep tdm-reservation. 1 = rights reserved (EU DSM Art. 4 opt-out), 0 = not reserved, absent = undeclared.",
        examples=[1],
        json_schema_extra={"x-iscc-context": "http://www.w3.org/ns/tdmrep#reservation"},
    )
    tdm_policy: AnyUrl | None = Field(
        None,
        description="URL of a TDM Policy document (typically a JSON-LD ODRL Offer profiling TDMRep). Semantically equivalent to W3C TDMRep tdm-policy.",
        examples=["https://example.com/tdmrep-policy.json"],
        json_schema_extra={"x-iscc-context": "http://www.w3.org/ns/tdmrep#policy"},
    )
